<?php
require("database1.php");
if(isset($_POST['insert']))
{
$customer_id                   = $_POST['customer_id'];
$finance_date                  = $_POST['finance_date'];
$emi_date                      = $_POST['emi_date'];
$firstname_bd                  = $_POST['firstname_bd'];
$last_name_bd                  = $_POST['last_name_bd'];
$gender_name_bd                = $_POST['gender_name_bd'];
$date_of_birth_bd              = $_POST['date_of_birth_bd'];
$age_bd                        = $_POST['age_bd'];
$occupation_bd                 = $_POST['occupation_bd'];
$houseof_bd                    = $_POST['houseof_bd'];
$mobile1_bd                    = $_POST['mobile1_bd'];
$mobile2_bd                    = $_POST['mobile2_bd'];
$so_wo_do_bd                   = $_POST['so_wo_do_bd'];
$door_no_bd                    = $_POST['door_no_bd'];
$flatno_premsis_bd             = $_POST['flatno_premsis_bd'];
$area_bd                       = $_POST['area_bd'];
$landmark_bd                   = $_POST['landmark_bd'];
$street_bd                     = $_POST['street_bd'];
$state_bd                      = $_POST['state_bd'];
$dist_bd                       = $_POST['dist_bd'];
$mandal_bd                     = $_POST['mandal_bd'];
$village_bd                    = $_POST['village_bd'];
$pin_code_bd                   = $_POST['pin_code_bd'];
$aadhar_no_bd                  = $_POST['aadhar_no_bd'];
$pan_no_bd                     = $_POST['pan_no_bd'];
$ration_no_bd                  = $_POST['ration_no_bd'];
$gas_consumerno_bd             = $_POST['gas_consumerno_bd'];
$gas_company_bd                = $_POST['gas_company_bd'];
$gas_dealer_bd                 = $_POST['gas_dealer_bd'];
$drviving_licence_bd           = $_POST['drviving_licence_bd'];
$passport_bd                   = $_POST['passport_bd'];
$ele_sec_no_bd                 = $_POST['ele_sec_no_bd'];
$voter_idno_bd                 = $_POST['voter_idno_bd'];
$kyc_upload_bd                 =time().$_FILES['kyc_upload_bd']['name'];
$type                          =$_FILES['kyc_upload_bd']['type'];
$temp_name                     =$_FILES['kyc_upload_bd']['tmp_name'];
$path                          ="uploads/images/".$kyc_upload_bd;
move_uploaded_file($temp_name,$path);
$firstname_gd1                 = $_POST['first_name_gd1'];
$last_name_gd1                 = $_POST['last_name_gd1'];
$gender_name_gd1               = $_POST['gendere_gd1'];
$date_of_birth_gd1             = $_POST['date_of_birthe_gd1'];
$age_gd1                       = $_POST['agee_gd1'];
$occupation_gd1                = $_POST['occupatione_gd1'];
$houseof_gd1                   = $_POST['houseof_gd1'];
$mobile1_gd1                   = $_POST['mobile1e_gd1'];
$mobile2_gd1                   = $_POST['mobile2e_gd1'];
$so_wo_do_gd1                 = $_POST['so_wo_doe_gd1'];
$door_no_gd1                    = $_POST['door_noe_gd1'];
$flatno_premsis_gd1            = $_POST['flatno_premsise_gd1'];
$area_gd1                      = $_POST['areae_gd1'];
$landmark_gd1                  = $_POST['landmarke_gd1'];
$street_gd1                    = $_POST['streete_gd1'];
$state_gd1                     = $_POST['state_gd1'];
$dist_gd1                      = $_POST['dist_gd1'];
$mandal_gd1                    = $_POST['mandal_gd1'];
$village_gd1                   = $_POST['village_gd1'];
$pin_code_gd1                  = $_POST['pin_code_gd1'];
$aadhar_no_gd1                 = $_POST['aadhar_noe_gd1'];
$pan_no_gd1                    = $_POST['pan_noe_gd1'];
$ration_no_gd1                 = $_POST['ration_noe_gd1'];
$voter_idno_gd1                = $_POST['voter_idnoe_gd1'];
$gas_consumerno_gd1            = $_POST['gas_consumerno_gd1'];
$gas_company_gd1               = $_POST['gas_company_gd1'];
$gas_dealer_gd1                = $_POST['gas_dealer_gd1'];
$drviving_licence_gd1          = $_POST['drviving_licence_gd1'];
$passport_gd1                  = $_POST['passport_gd1'];
$ele_sec_no_gd1                = $_POST['ele_sec_noe_gd1'];
$kyc_upload_gd1                 =time().$_FILES['kyc_upload_gd1']['name'];
$type                          =$_FILES['kyc_upload_gd1']['type'];
$temp_name                     =$_FILES['kyc_upload_gd1']['tmp_name'];
$path                          ="uploads/images/".$kyc_upload_gd1;
move_uploaded_file($temp_name,$path);
$firstname_gd2                 = $_POST['first_name_gd2'];
$last_name_gd2                = $_POST['last_name_gd2'];
$gender_name_gd2               = $_POST['gender_gd2'];
$date_of_birth_gd2             = $_POST['date_of_birth_gd2'];
$age_gd2                       = $_POST['age_gd2'];
$occupation_gd2                = $_POST['occupation_gd2'];
$houseof_gd2                   = $_POST['house_of_gd2'];
$mobile1_gd2                  = $_POST['mobile1_gd2'];
$mobile2_gd2                   = $_POST['mobile2_gd2'];
$so_wo_do_gd2                 = $_POST['so_wo_do_gd2'];
$door_no_gd2                    = $_POST['door_no_gd2'];
$flatno_premsis_gd2            = $_POST['flatno_premsis_gd2'];
$area_gd2                      = $_POST['area_gd2'];
$landmark_gd2                  = $_POST['landmark_gd2'];
$street_gd2                    = $_POST['street_gd2'];
$state_gd2                     = $_POST['state_gd2'];
$dist_gd2                      = $_POST['dist_gd2'];
$mandal_gd2                    = $_POST['mandal_gd2'];
$village_gd2                   = $_POST['village_gd2'];
$pin_code_gd2                  = $_POST['pin_code_gd2'];
$aadhar_no_gd2                = $_POST['aadhar_no_gd2'];
$pan_no_gd2                    = $_POST['pan_no_gd2'];
$ration_no_gd2                 = $_POST['ration_no_gd2'];
$voter_idno_gd2               = $_POST['voter_idno_gd2'];
$gas_consumerno_gd2            = $_POST['gas_consumerno_gd2'];
$gas_company_gd2               = $_POST['gas_company_gd2'];
$gas_dealer_gd2                = $_POST['gas_dealer_gd2'];
$drviving_licence_gd2          = $_POST['drviving_licence_gd2'];
$passport_gd2                 = $_POST['passport_gd2'];
$ele_sec_no_gd2                = $_POST['ele_sec_no_gd2'];
$kyc_upload_gd2                 =time().$_FILES['kyc_upload_gd2']['name'];
$type                          =$_FILES['kyc_upload_gd2']['type'];
$temp_name                     =$_FILES['kyc_upload_gd2']['tmp_name'];
$path                          ="uploads/images/".$kyc_upload_gd2;
move_uploaded_file($temp_name,$path);
$brand                         = $_POST['brand'];
$class                         = $_POST['class'];
$vechicle_no                   = $_POST['vechicle_no'];
$vechicle_trno                 = $_POST['vechicle_trno'];
$vechicle_type                 = $_POST['vechicle_type'];
$model                         = $_POST['model'];
$wheels                        = $_POST['wheels'];
$vechicle_value                = $_POST['vechicle_value'];
$engine_no                     = $_POST['engine_no'];
$chassis_no                    = $_POST['chassis_no'];
$rc                            = $_POST['rc'];
$noc                           = $_POST['noc'];
$duplicate_key                 = $_POST['duplicate_key'];
$init_payment                  = $_POST['init_payment'];
$dp_due01                      = $_POST['dp_due01'];
$due_date01                    = $_POST['due_date01'];
$dp_due02                      = $_POST['dp_due02'];
$due_date02                    = $_POST['due_date02'];
$finance_amount                = $_POST['finance_amount'];
$intrest_amount                = $_POST['intrest_amount'];
$total                         = $_POST['total'];
$no_of_emis                    = $_POST['no_of_emis'];
$emi_amount                    = $_POST['emi_amount'];
$mode_of_payment               = $_POST['mode_of_payment'];
$branch                        = $_POST['branch'];
$line_code                     = $_POST['line_code'];
$insert = "INSERT INTO `newborrowers`(`customer_id`, `finance_date`, `emi_date`, `firstname_bd`, `last_name_bd`, `gender_name_bd`, `date_of_birth_bd`, `age_bd`, `occupation_bd`, `houseof_bd`, `mobile1_bd`, `mobile2_bd`, `so_wo_do_bd`, `door_no_bd`, `flatno_premsis_bd`, `area_bd`, `landmark_bd`, `street_bd`, `state_bd`, `dist_bd`, `mandal_bd`, `village_bd`, `pin_code_bd`, `aadhar_no_bd`, `pan_no_bd`, `ration_no_bd`, `voter_idno_bd`, `gas_consumerno_bd`, `gas_company_bd`, `gas_dealer_bd`, `drviving_licence_bd`, `passport_bd`, `ele_sec_no_bd`, `kyc_upload_bd`, `first_name_gd1`, `last_name_gd1`, `gender_gd1`, `date_of_birthe_gd1`, `age_gd1`, `occupation_gd1`, `houseof_gd1`, `mobile1_gd1`, `mobile2_gd1`, `so_wo_do_gd1`, `door_no_gd1`, `flatno_premsise_gd1`, `area_gd1`, `landmark_gd1`, `street_gd1`, `state_gd1`, `dist_gd1`, `mandal_gd1`, `village_gd1`, `pin_code_gd1`, `aadhar_noe_gd1`, `pan_no_gd1`, `ration_no_gd1`, `voter_idno_gd1`, `gas_consumerno_gd1`, `gas_company_gd1`, `gas_dealer_gd1`, `drviving_licence_gd1`, `passport_gd1`, `ele_sec_noe_gd1`, `kyc_uploade_gd1`, `first_name_gd2`, `last_name_gd2`, `gender_gd2`, `date_of_birth_gd2`, `age_gd2`, `occupation_gd2`, `house_of_gd2`, `mobile1_gd2`, `mobile2_gd2`, `so_wo_do_gd2`, `door_no_gd2`, `flatno_premsis_gd2`, `area_gd2`, `landmark_gd2`, `street_gd2`, `state_gd2`, `dist_gd2`, `mandal_gd2`, `village_gd2`, `pin_code_gd2`, `aadhar_no_gd2`, `pan_no_gd2`, `ration_no_gd2`, `voter_idno_gd2`, `gas_consumerno_gd2`, `gas_company_gd2`, `gas_dealer_gd2`, `drviving_licence_gd2`, `passport_gd2`, `ele_sec_no_gd2`, `kyc_upload_gd2`, `brand`, `class`, `vechicle_no`, `vechicle_trno`, `vechicle_type`, `model`, `wheels`, `vechicle_value`, `engine_no`, `chassis_no`, `rc`, `noc`, `duplicate_key`, `init_payment`, `dp_due01`, `due_date01`, `dp_due02`, `due_date02`, `finance_amount`, `intrest_amount`, `total`, `no_of_emis`, `emi_amount`, `mode_of_payment`, `branch`, `line_code`) VALUES('$customer_id','$finance_date','$emi_date','$firstname_bd','$last_name_bd','$gender_name_bd','$date_of_birth_bd','$age_bd','$occupation_bd','$houseof_bd','$mobile1_bd','$mobile2_bd','$so_wo_do_bd','$door_no_bd','$flatno_premsis_bd','$area_bd','$landmark_bd','$street_bd','$state_bd','$dist_bd','$mandal_bd','$village_bd','$pin_code_bd','$aadhar_no_bd','$pan_no_bd','$ration_no_bd','$gas_consumerno_bd','$gas_company_bd','$gas_dealer_bd','$drviving_licence_bd','$passport_bd','$ele_sec_no_bd','$voter_idno_bd','$kyc_upload_bd','$firstname_gd1','$last_name_gd1','$gender_name_gd1','$date_of_birth_gd1','$age_gd1','$occupation_gd1','$houseof_gd1','$mobile1_gd1','$mobile2_gd1','$so_wo_do_gd1','$door_no_gd1','$flatno_premsis_gd1','$area_gd1','$landmark_gd1','$street_gd1','$state_gd1','$dist_gd1','$mandal_gd1','$village_gd1','$pin_code_gd1','$aadhar_no_gd1','$pan_no_gd1','$ration_no_gd1','$voter_idno_gd1','$gas_consumerno_gd1','$gas_company_gd1','$gas_dealer_gd1','$drviving_licence_gd1','$passport_gd1','$ele_sec_no_gd1','$kyc_upload_gd1','$firstname_gd2','$last_name_gd2','$gender_name_gd2','$date_of_birth_gd2','$age_gd2','$occupation_gd2','$houseof_gd2','$mobile1_gd2','$mobile2_gd2','$so_wo_do_gd2','$door_no_gd2','$flatno_premsis_gd2','$area_gd2','$landmark_gd2','$street_gd2','$state_gd2','$dist_gd2','$mandal_gd2','$village_gd2','$pin_code_gd2','$aadhar_no_gd2','$pan_no_gd2','$ration_no_gd2','$voter_idno_gd2','$gas_consumerno_gd2','$gas_company_gd2','$gas_dealer_gd2','$drviving_licence_gd2','$passport_gd2','$ele_sec_no_gd2','$kyc_upload_gd2','$brand','$class','$vechicle_no','$vechicle_trno','$vechicle_type','$model','$wheels','$vechicle_value','$engine_no','$chassis_no','$rc','$noc','$duplicate_key','$init_payment','$dp_due01','$due_date01','$dp_due02','$due_date02','$finance_amount','$intrest_amount','$total','$no_of_emis','$emi_amount','$mode_of_payment','$branch','$line_code')";
if(mysqli_query($connection, $insert))
	{
	  
		echo "data updated";
		//header("location:accountview.php");
	} else{
	    //$_SESSION["msg"] = "UNABLE TO INSERT" ;
	    	//header("location:accountview.php");
		echo  "data updatation failed";
	}
    
}
?>