<?php
require('database1.php');
$table="CREATE TABLE newborrowers
(
id int NOT NULL AUTO_INCREMENT,
customer_id  varchar(100),
finance_date varchar(100),
emi_date      varchar(100),
firstname_bd      varchar(100),
last_name_bd        varchar(100),
gender_name_bd    varchar(100),
date_of_birth_bd  varchar(100),
age_bd           varchar(100),
occupation_bd      varchar(100),
houseof_bd          varchar(100),
mobile1_bd         varchar(100),
mobile2_bd         varchar(100),
so_wo_do_bd         varchar(100),
door_no_bd          varchar(100),
flatno_premsis_bd   varchar(100),
area_bd             varchar(100),
landmark_bd         varchar(100),
street_bd           varchar(100),
state_bd            varchar(100),
dist_bd             varchar(100),
mandal_bd           varchar(100),
village_bd          varchar(100),
pin_code_bd         varchar(100),
aadhar_no_bd       varchar(100),
pan_no_bd            varchar(100),
ration_no_bd        varchar(100),
voter_idno_bd        varchar(100),
gas_consumerno_bd    varchar(100),
gas_company_bd        varchar(100),
gas_dealer_bd        varchar(100),
drviving_licence_bd   varchar(100),
passport_bd           varchar(100),
ele_sec_no_bd        varchar(100),
kyc_upload_bd         varchar(100),
first_name_gd1    varchar(100),
last_name_gd1      varchar(100),
gender_gd1         varchar(100),
date_of_birthe_gd1 varchar(100),
age_gd1            varchar(100),
occupation_gd1      varchar(100),
houseof_gd1         varchar(100),
mobile1_gd1         varchar(100),
mobile2_gd1         varchar(100),
so_wo_do_gd1        varchar(100),
door_no_gd1          varchar(100),
flatno_premsise_gd1   varchar(100),
area_gd1             varchar(100),
landmark_gd1         varchar(100),
street_gd1           varchar(100),
state_gd1            varchar(100),
dist_gd1             varchar(100),
mandal_gd1           varchar(100),
village_gd1          varchar(100),
pin_code_gd1         varchar(100),
aadhar_noe_gd1        varchar(100),
pan_no_gd1            varchar(100),
ration_no_gd1         varchar(100),
voter_idno_gd1        varchar(100),
gas_consumerno_gd1    varchar(100),
gas_company_gd1         varchar(100),
gas_dealer_gd1          varchar(100),
drviving_licence_gd1   varchar(100),
passport_gd1           varchar(100),
ele_sec_noe_gd1         varchar(100),
kyc_uploade_gd1         varchar(100),
first_name_gd2   varchar(100),
last_name_gd2      varchar(100),
gender_gd2         varchar(100),
date_of_birth_gd2  varchar(100),
age_gd2            varchar(100),
occupation_gd2      varchar(100),
house_of_gd2         varchar(100),
mobile1_gd2        varchar(100),
mobile2_gd2         varchar(100),
so_wo_do_gd2       varchar(100),
door_no_gd2          varchar(100),
flatno_premsis_gd2   varchar(100),
area_gd2             varchar(100),
landmark_gd2         varchar(100),
street_gd2           varchar(100),
state_gd2            varchar(100),
dist_gd2             varchar(100),
mandal_gd2           varchar(100),
village_gd2         varchar(100),
pin_code_gd2        varchar(100),
aadhar_no_gd2        varchar(100),
pan_no_gd2            varchar(100),
ration_no_gd2         varchar(100),
voter_idno_gd2        varchar(100),
gas_consumerno_gd2   varchar(100),         
gas_company_gd2        varchar(100),
gas_dealer_gd2           varchar(100),
drviving_licence_gd2   varchar(100),
passport_gd2           varchar(100),
ele_sec_no_gd2        varchar(100),
kyc_upload_gd2         varchar(100),
brand              varchar(100),
class              varchar(100),
vechicle_no        varchar(100),
vechicle_trno      varchar(100),
vechicle_type       varchar(100),
model               varchar(100),
wheels              varchar(100),
vechicle_value      varchar(100),
engine_no           varchar(100),
chassis_no          varchar(100),
rc                  varchar(100),
noc                varchar(100),
duplicate_key         varchar(100),
init_payment        varchar(100),
dp_due01            varchar(100),
due_date01              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
dp_due02            varchar(100),
due_date02              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
finance_amount       varchar(100),
intrest_amount       varchar(100),
total                 varchar(100),
no_of_emis            varchar(100),
emi_amount            varchar(100),
mode_of_payment       varchar(100),
branch                 varchar(100),
line_code              varchar(100),
PRIMARY KEY (id)
 
)";

if (mysqli_query($connection, $table)) {
    echo "Table test created successfully";
}
 else {
    echo "Error creating table: " . mysqli_error($connection);
}

mysqli_close($connection);

?>